import { useState } from "react";
import { ChevronDown, Mail } from "lucide-react";
import { UI, TopNav } from "./shared.jsx";
import { useAuth } from "./auth/AuthContext.jsx";

function FaqItem({ question, children, defaultOpen = false }) {
  const [open, setOpen] = useState(defaultOpen);
  return (
    <div className="rounded-xl border" style={{ borderColor: UI.line, background: UI.card }}>
      <button
        type="button"
        onClick={() => setOpen((o) => !o)}
        className="w-full flex items-center justify-between gap-3 px-4 sm:px-5 py-3.5 text-left"
      >
        <span className="font-body text-sm font-semibold" style={{ color: UI.ink }}>{question}</span>
        <ChevronDown size={16} style={{ color: UI.inkSoft, transform: open ? "rotate(180deg)" : "none", transition: "transform 0.15s", flexShrink: 0 }} />
      </button>
      {open && (
        <div className="px-4 sm:px-5 pb-4 pt-0.5 border-t" style={{ borderColor: UI.line }}>
          <div className="font-body text-sm pt-3.5 space-y-2" style={{ color: UI.inkSoft, lineHeight: 1.65 }}>
            {children}
          </div>
        </div>
      )}
    </div>
  );
}

function Ol({ children }) {
  return <ol className="list-decimal pl-5 space-y-1.5">{children}</ol>;
}

function Section({ title, children }) {
  return (
    <div className="mb-9">
      <h2 className="font-display font-bold text-lg mb-3" style={{ color: UI.ink }}>{title}</h2>
      <div className="grid gap-2.5">{children}</div>
    </div>
  );
}

export function HelpPage({ onSwitchTool, onGoHome }) {
  const { user, logout } = useAuth();

  return (
    <div className="min-h-dvh" style={{ background: UI.page }}>
      <TopNav active="help" onSwitch={onSwitchTool} userName={user?.fullName} onLogout={logout} onLogoClick={onGoHome} />
      <div className="max-w-3xl mx-auto px-3 sm:px-6 py-6 sm:py-10">
        <h1 className="font-display font-bold text-2xl mb-1" style={{ color: UI.ink }}>Help</h1>
        <p className="font-body text-sm mb-8" style={{ color: UI.inkSoft }}>
          Quick answers for the most common things agents ask about.
        </p>

        <Section title="Your brand info">
          <FaqItem question="How do I change my headshot?" defaultOpen>
            <Ol>
              <li>Go to <strong>Profile</strong> in the top-right, then the <strong>Brand</strong> tab (it opens there by default).</li>
              <li>Click the <strong>Headshot</strong> box and choose a new photo from your device.</li>
              <li>Click <strong>Save brand settings</strong> at the bottom.</li>
            </Ol>
            <p>Your new headshot applies to every post you create from then on — nothing needs to be regenerated by hand.</p>
          </FaqItem>

          <FaqItem question="How do I update my brokerage logo?">
            <Ol>
              <li>Go to <strong>Profile → Brand</strong>.</li>
              <li>Click the <strong>Logo</strong> box next to your headshot and choose an image file.</li>
              <li>Click <strong>Save brand settings</strong>.</li>
            </Ol>
            <p>A logo with a transparent background (PNG) looks best, since it sits directly on the contact band of every post.</p>
          </FaqItem>

          <FaqItem question="How do I update my phone number or other contact info?">
            <Ol>
              <li>Go to <strong>Profile → Brand</strong>.</li>
              <li>Update <strong>Cell Phone</strong>, <strong>Email</strong>, <strong>Website</strong>, <strong>Brokerage</strong>, <strong>Office City</strong>, <strong>Office Phone</strong>, or <strong>License Number</strong> in the form fields.</li>
              <li>Click <strong>Save brand settings</strong>.</li>
            </Ol>
            <p>The preview on the right updates live so you can check how it'll look before saving.</p>
          </FaqItem>

          <FaqItem question="Can I change my brand color or script font?">
            <p>
              Yes — still under <strong>Profile → Brand</strong>. Pick a preset swatch or click <strong>Custom</strong> for any color, and choose a
              script font from the dropdown. Both apply to new posts immediately after saving.
            </p>
          </FaqItem>
        </Section>

        <Section title="Creating and downloading posts">
          <FaqItem question="How do I download a post?">
            <Ol>
              <li>Open the <strong>Listings</strong> tool and build your post (photo, template, headline, etc.).</li>
              <li>Pick a size from the aspect-ratio tabs (Square, Story, Landscape, Portrait).</li>
              <li>Click <strong>Download</strong>. On a phone, this opens your native share sheet instead of a direct download.</li>
            </Ol>
          </FaqItem>

          <FaqItem question='What does "Download All" do?'>
            <p>
              It generates every social size (square, story, landscape, and portrait) for the post you've built and downloads all of them
              one after another, so you don't have to switch sizes and re-download manually.
            </p>
          </FaqItem>

          <FaqItem question="Can I post straight to Facebook?">
            <p>
              Yes — the <strong>Share to Facebook</strong> button uses your phone's share sheet where available. On desktop, or if direct
              sharing isn't supported, it downloads the image and opens Facebook so you can attach it yourself.
            </p>
          </FaqItem>

          <FaqItem question="My download didn't work / opened a blank tab. What happened?">
            <p>
              This usually means your headshot or logo was loaded from a link that blocks downloads. Save that image to your device and
              re-upload it in the Headshot/Logo box under <strong>Profile → Brand</strong>, then try downloading again.
            </p>
          </FaqItem>
        </Section>

        <Section title="Past posts">
          <FaqItem question="Where can I find posts I've already made?">
            <Ol>
              <li>Go to <strong>Profile</strong>, then the <strong>Past Posts</strong> tab.</li>
              <li>Every post you've downloaded or shared shows up there, newest first.</li>
            </Ol>
          </FaqItem>

          <FaqItem question="How do I re-download a past post?">
            <p>Hover (or tap, on mobile) a post in <strong>Profile → Past Posts</strong> and click the download icon that appears.</p>
          </FaqItem>

          <FaqItem question="How do I delete a past post?">
            <p>
              Hover the post and click the trash icon, then confirm. This only removes it from your history — it doesn't affect any copy
              you've already posted or downloaded elsewhere.
            </p>
          </FaqItem>
        </Section>

        <Section title="Account">
          <FaqItem question="How do I change my password?">
            <p>Go to <strong>Profile → Account</strong> and fill in your current and new password, then click <strong>Update password</strong>.</p>
          </FaqItem>
          <FaqItem question="I forgot my password.">
            <p>On the login screen, click <strong>Forgot password?</strong> and follow the emailed reset link.</p>
          </FaqItem>
        </Section>

        <div className="rounded-2xl border p-5 sm:p-6 flex items-center gap-3" style={{ borderColor: UI.line, background: UI.card }}>
          <div className="flex items-center justify-center rounded-full flex-shrink-0" style={{ width: 36, height: 36, background: UI.stone }}>
            <Mail size={16} style={{ color: UI.ink }} />
          </div>
          <div>
            <p className="font-body text-sm font-semibold" style={{ color: UI.ink }}>Still stuck?</p>
            <p className="font-body text-xs mt-0.5" style={{ color: UI.inkSoft }}>
              Email us at{" "}
              <a href="mailto:support@postkey.app" className="font-semibold underline" style={{ color: UI.ink }}>support@postkey.app</a>{" "}
              and we'll help you out.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
